export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST'
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS'
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL'

export const GET_ALL_TRANSACTIONS_REQUEST = 'GET_ALL_TRANSACTIONS_REQUEST'
export const GET_ALL_TRANSACTIONS_SUCCESS = 'GET_ALL_TRANSACTIONS_SUCCESS'
export const GET_ALL_TRANSACTIONS_FAIL = 'GET_ALL_TRANSACTIONS_FAIL'

export const GET_EXPENSES_REQUEST = 'GET_EXPENSES_REQUEST'
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS'
export const GET_EXPENSES_FAIL = 'GET_EXPENSES_FAIL'

export const GET_SAVINGS_REQUEST = 'GET_SAVINGS_REQUEST'
export const GET_SAVINGS_SUCCESS = 'GET_SAVINGS_SUCCESS'
export const GET_SAVINGS_FAIL = 'GET_SAVINGS_FAIL'

export const GET_OTHER_REQUEST = 'GET_OTHER_REQUEST'
export const GET_OTHER_SUCCESS = 'GET_OTHER_SUCCESS'
export const GET_OTHER_FAIL = 'GET_OTHER_FAIL'

export const DELETE_EXPENSE_TRANSACTION_REQUEST =
    'DELETE_EXPENSE_TRANSACTION_REQUEST'
export const DELETE_EXPENSE_TRANSACTION_SUCCESS =
    'DELETE_EXPENSE_TRANSACTION_SUCCESS'
export const DELETE_EXPENSE_TRANSACTION_FAIL = 'DELETE_EXPENSE_TRANSACTION_FAIL'

export const DELETE_SAVINGS_TRANSACTION_REQUEST =
    'DELETE_SAVINGS_TRANSACTION_REQUEST'
export const DELETE_SAVINGS_TRANSACTION_SUCCESS =
    'DELETE_SAVINGS_TRANSACTION_SUCCESS'
export const DELETE_SAVINGS_TRANSACTION_FAIL = 'DELETE_SAVINGS_TRANSACTION_FAIL'
